UPDATE seniorprojects set FirstName='Alex' where CONCAT(FirstName,' ',LastName)='A. Dekhtyar';
UPDATE seniorprojects set FirstName='Alex' where CONCAT(FirstName,' ',LastName)='Aleks Dekhtyar';
UPDATE seniorprojects set LastName='Dekhtyar' where CONCAT(FirstName,' ',LastName)='Alex DexT?pb';
UPDATE seniorprojects set FirstName='Alex' where CONCAT(FirstName,' ',LastName)='Alexander Dekhtyar';
UPDATE seniorprojects set FirstName='Alex' where CONCAT(FirstName,' ',LastName)='Александр Dekhtyar';
UPDATE seniorprojects set FirstName='Hisham', LastName='Assal' where CONCAT(FirstName,' ',LastName)='Assal Hisham';
UPDATE seniorprojects set FirstName='Chris' where CONCAT(FirstName,' ',LastName)='Christopher Lupo';
UPDATE seniorprojects set FirstName='Charles' where CONCAT(FirstName,' ',LastName)='Chuck Dana';
UPDATE seniorprojects set FirstName='Clint' where CONCAT(FirstName,' ',LastName)='Clinton Staley';
UPDATE seniorprojects set FirstName='David' where CONCAT(FirstName,' ',LastName)='D. Janzen';
UPDATE seniorprojects set FirstName='Alex', LastName='Dekhtyar' where CONCAT(FirstName,' ',LastName)='Dekhtyar Alexander';
UPDATE seniorprojects set LastName='Kurfess' where CONCAT(FirstName,' ',LastName)='Franz Kurzes';
UPDATE seniorprojects set FirstName='Franz' where CONCAT(FirstName,' ',LastName)='Franz. Kurfess';
UPDATE seniorprojects set FirstName='David' where CONCAT(FirstName,' ',LastName)='Hugh Dave Retz';
UPDATE seniorprojects set FirstName='John' where CONCAT(FirstName,' ',LastName)='J. Clements';
UPDATE seniorprojects set FirstName='Franz' where CONCAT(FirstName,' ',LastName)='John Franz Kurfess';
UPDATE seniorprojects set FirstName='Phillip' where CONCAT(FirstName,' ',LastName)='Phil Nico';
UPDATE seniorprojects set FirstName='Tim' where CONCAT(FirstName,' ',LastName)='Timothy Kearns';
UPDATE seniorprojects set FirstName='Zoë' where CONCAT(FirstName,' ',LastName)='Z. Wood';
UPDATE seniorprojects set FirstName='Zoë' where CONCAT(FirstName,' ',LastName)='Zoe Wood';